name: Kubescape
description: run kubescape scans against Kubernetes manifests
author: https://github.com/rossedman
configuration:
  properties:
    directory:
      type: string
      default: config
    format:
      type: string
      default: json
      enum:
        - json
        - junit
        - pdf
    framework:
      type: string
      enum:
        - nsa
        - mitre
    results:
      type: string
      default: results.json
  additionalProperties: false