name: Kubescape
description: run kubescape scans against Kubernetes manifests
author: https://github.com/rossedman
configuration:
  properties:
    directory:
      type: string
      default: config
    framework:
      type: string
      enum:
        - nsa
        - mitre
  additionalProperties: false