#!/usr/bin/env bash
set -e
set -o pipefail
set -u

main() {
    echo '--- Running scan'
    if ! [ -x "$(command -v kubescape)" ]; then
        echo 'Error: kubescape is not installed.' >&2
        exit 1
    fi

    echo "$BUILDKITE_PLUGIN_KUBESCAPE_DIRECTORY"
    echo "$BUILDKITE_PLUGIN_KUBESCAPE_FRAMEWORK"
}

main