#!/usr/bin/env bash
set -e
set -o pipefail
set -u

main() {
    echo '--- Running kubescape scan'
    if ! [ -x "$(command -v kubescape)" ]; then
        echo 'Error: kubescape is not installed.' >&2
        exit 1
    fi

    CONFIG="$BUILDKITE_PLUGIN_KUBESCAPE_DIRECTORY"
    FORMAT="$BUILDKITE_PLUGIN_KUBESCAPE_FORMAT"
    FRAMEWORK="$BUILDKITE_PLUGIN_KUBESCAPE_FRAMEWORK"
    RESULTS="$BUILDKITE_PLUGIN_KUBESCAPE_RESULTS"

    kubescape scan framework ${FRAMEWORK} ${CONFIG}/**/*.yaml \
        --format $FORMAT --output $RESULTS
}

main