#!/usr/bin/env bash
set -e
set -o pipefail
set -u

main() {
    echo '--- Running scan'
    if ! [ -x "$(command -v kubescape)" ]; then
        echo 'Error: kubescape is not installed.' >&2
        exit 1
    fi

    CONFIG="$BUILDKITE_PLUGIN_KUBESCAPE_DIRECTORY"
    FRAMEWORK="$BUILDKITE_PLUGIN_KUBESCAPE_FRAMEWORK"

    kubescape scan framework ${FRAMEWORK} ${CONFIG}/**/*.yaml
}

main